### ISSUE TITLE
Pretty good.

### ISSUE THREAD

**Issue by Vulner1** [DaEpicSwag/Roblox-Cookie-Logger#1]
Good, but your gonna get a lot of people complaining that it wont work since most people who look at this don’t know how to install third party library's you should try using urllib. I would also recommend adding a IP logger.

**Comment by DaEpicSwag** [comment]
On it! I’m adding a discord token logger (with ip and all of that) and I’m pretty sure it will be even better soon since I’m adding a bunch of more features. About the third party stuff, I’ll just put in the README on how to do that. Btw I suggest using Nuitka to compile since pyinstaller is a nightmare.

**Comment by weaveriku** [comment]
What is a ENCODED BASE32 HOOK HEREEEE??? Pls help!

**Comment by weaveriku** [comment]
is it just a encoded webhook?

**Comment by Vulner1** [comment]
> What is a ENCODED BASE32 HOOK HEREEEE??? Pls help!

**Comment by Vulner1** [comment]
> is it just a encoded webhook?



> What is a ENCODED BASE32 HOOK HEREEEE??? Pls help!

What’s wrong?

**Comment by DaEpicSwag** [comment]
> is it just a encoded webhook?

Yes

**Comment by qertyuiop12345678** [comment]
> > is it just a encoded webhook?
> 
> > What is a ENCODED BASE32 HOOK HEREEEE??? Pls help!
> 
> What’s wrong?

https://emn178.github.io/online-tools/base32_encode.html

**Comment by DaEpicSwag** [comment]
@qertyuiop12345678 thank you

**Comment by qExoticBalls** [comment]
ModuleNotFoundError: No module named 'browser_cookie3' . Im used to having requirements.txt file in these downloads which u pip install but with this one im just confused 0_0

**Comment by Enterrados** [comment]
> browser_cookie3

just type "pip install browser_cookie3" on cmd and click enter <3
