### ISSUE TITLE
XSS vulnerability patches

### ISSUE THREAD

**Issue by CoderLucid** [DaEpicSwag/Roblox-Cookie-Logger#16]
Hey, I'm intrigued with the project you are doing here but don't you think that it's a bit outdated? Roblox has added new security measures to make sure stuff like this doesn't happen. From my knowledge, **roblox (Chrome) 403's all get cookies functions** from / related to a 3 party source. Only way I could see this actually working is if a whole browser where to be hooked / would have direct control of the browser.  Would simply inject Advanced logger.py into the browser via beef fix the issue?

Correct me if I am wrong, also keep me updated on the progress.

**Comment by DaEpicSwag** [comment]
It uses a module to get extract the cookies which is completely possible, then sends it to a webhook. Simple.

**Comment by DaEpicSwag** [comment]
This has nothing to do with xss
