### ISSUE TITLE
advance logger

### ISSUE THREAD

**Issue by jsjsnej** [DaEpicSwag/Roblox-Cookie-Logger#2]
why does the built in token thing not work?

![image](https://user-images.githubusercontent.com/61519579/110347387-93060c80-7ffe-11eb-8888-b4604812aa99.png)

**Comment by DaEpicSwag** [comment]
Pretty sure it’s something wrong with the JSON code, I’ll look into it.

**Comment by jsjsnej** [comment]
> Pretty sure it’s something wrong with the JSON code, I’ll look into it.

okay, thank you

**Comment by DaEpicSwag** [comment]
Yup I fixed it. Try editing line 233.
