### ISSUE TITLE
🤣  Skids

### ISSUE THREAD

**Issue by NotSwaraj** [DaEpicSwag/Roblox-Cookie-Logger#23]
You say you made it right?
🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 
https://github.com/sslprograms/robloxcookielogger - I wonder what this is, retard.
Your so fucking cringy lmao.

**Comment by DaEpicSwag** [comment]
well this was made by me and some other friends, plus there was a project up in september like this but github termed by acc

**Comment by DaEpicSwag** [comment]
idk but the only retard here is you

**Comment by NotSwaraj** [comment]
lmaooooooo eat ass
