### ISSUE TITLE
Great logger, but I have an issue.

### ISSUE THREAD

**Issue by Onevillain1** [DaEpicSwag/Roblox-Cookie-Logger#8]
Hello there, thanks for reading.

My logger has no issues and works perfectly with the **.py** extention, but when I try using Nuitka I get the following:

FATAL:
Error, specify only one positional argument unless "--run" is specified to
pass them to the compiled program execution.

I am using the shell and writing **python -m nuitka myfile.py** would like some help, thanks.

**Comment by qertyuiop12345678** [comment]
Thats a nuitka problrm lmao.
